[package]
name = "firebase-rs"
edition = "2021"
version = "2.0.4"
description = "Rust based Firebase library"
readme = "README.md"
repository = "https://github.com/emreyalvac/firebase-rs"
documentation = "https://docs.rs/firebase-rs/2.0.4/firebase_rs/"
license = "MIT"
authors = ["Emre YALVAÃ‡ <emre.yalvac@outlook.com>"]
exclude = ["examples/*", "tests/*"]
keywords = ["firebase", "rest", "api", "web", "database"]

[dependencies]
url = "2.2.2"
reqwest = { version = "0.11.11", features = ["json"] }
serde_json = "1.0.82"
serde = { version = "1.0.139", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1.20.0", features = ["rt", "macros"] }
